#!/usr/bin/env python3
import sys, getopt, json, random, os
from datetime import datetime, timedelta
import requests

def usage():
    print('dbFill.py -u <baseurl> -p <port> -n <numUsers> -t <numTasks>')

def main(argv):
    baseurl = "localhost"
    port = 3000
    userCount = 50
    taskCount = 200

    try:
        opts, _ = getopt.getopt(argv,"hu:p:n:t:",["url=","port=","users=","tasks="])
    except getopt.GetoptError:
        usage(); sys.exit(2)
    for opt, arg in opts:
        if opt == '-h': usage(); sys.exit()
        elif opt in ("-u","--url"): baseurl = str(arg)
        elif opt in ("-p","--port"): port = int(arg)
        elif opt in ("-n","--users"): userCount = int(arg)
        elif opt in ("-t","--tasks"): taskCount = int(arg)

    base = f"http://{baseurl}:{port}/api"
    headers = {"Content-Type":"application/json"}

    firstNames = ["james","john","robert","michael","william","david","richard","charles","joseph","thomas","christopher","daniel","paul","mark","donald","george","kenneth","steven","edward","brian","ronald","anthony","kevin","jason","matthew","gary","timothy","jose","larry","jeffrey","frank","scott","eric","stephen","andrew","raymond","gregory","joshua","jerry","dennis","walter","patrick","peter","harold","douglas","henry","carl","arthur","ryan","roger","joe","juan","jack","albert","jonathan","justin","terry","gerald","keith","samuel","willie","ralph","lawrence","nicholas","roy","benjamin","bruce","brandon","adam","harry","fred","wayne","billy","steve","louis","jeremy","aaron","randy","howard","eugene","carlos","russell","bobby","victor","martin","ernest","phillip","todd","jesse","craig","alan","shawn","clarence","sean","philip","chris","johnny","earl","jimmy","antonio","danny","bryan","tony","luis","mike","stanley","leonard","nathan","dale","manuel","rodney","curtis","norman","allen","marvin","vincent","glenn","jeffery","travis","jeff","chad","jacob","lee","melvin","alfred","kyle","francis","bradley","jesus","herbert","frederick","ray","joel","edwin","don","eddie","ricky","troy","randall","barry","alexander","bernard","mario","leroy","francisco","marcus","micheal","theodore","clifford","miguel","oscar","jay","jim","tom","calvin","alex","jon","ronnie","bill","lloyd","tommy","leon","derek","warren","darrell","jerome","floyd","leo","alvin","tim","wesley","gordon","dean","greg","jorge","dustin","pedro","derrick","dan","lewis","zachary","corey","herman","maurice","vernon","roberto","clyde","glen","hector","shane","ricardo","sam","rick","lester","brent","ramon","charlie","tyler","gilbert","gene"]
    lastNames  = ["smith","johnson","williams","jones","brown","davis","miller","wilson","moore","taylor","anderson","thomas","jackson","white","harris","martin","thompson","garcia","martinez","robinson","clark","rodriguez","lewis","lee","walker","hall","allen","young","hernandez","king","wright","lopez","hill","scott","green","adams","baker","gonzalez","nelson","carter","mitchell","perez","roberts","turner","phillips","campbell","parker","evans","edwards","collins","stewart","sanchez","morris","rogers","reed","cook","morgan","bell","murphy","bailey","rivera","cooper","richardson","cox","howard","ward","torres","peterson","gray","ramirez","james","watson","brooks","kelly","sanders","price","bennett","wood","barnes","ross","henderson","coleman","jenkins","perry","powell","long","patterson","hughes","flores","washington","butler","simmons","foster","gonzales","bryant","alexander","russell","griffin","diaz","hayes"]

    script_dir = os.path.dirname(os.path.abspath(__file__))
    tasks_path = os.path.join(script_dir, "tasks.txt")
    with open(tasks_path, "r") as f:
        taskNames = [line.strip() for line in f if line.strip()]

    userIDs, userNames, userEmails = [], [], []

    for _ in range(userCount):
        fn, ln = random.choice(firstNames), random.choice(lastNames)
        name = f"{fn} {ln}"
        email = f"{fn}@{ln}.com"
        r = requests.post(f"{base}/users", headers=headers, json={"name":name, "email":email})
        j = r.json()
        if r.status_code >= 400 or not j.get("data"):
            continue
        u = j["data"]
        userIDs.append(u["_id"]); userNames.append(u["name"]); userEmails.append(u["email"])

    for _ in range(taskCount):
        assigned = random.randint(0,10) > 4 and len(userIDs) > 0
        idx = random.randrange(len(userIDs)) if assigned else -1
        assignedUserID = userIDs[idx] if assigned else ""
        assignedUserName = userNames[idx] if assigned else "unassigned"
        completed = random.randint(0,10) > 5
        deadline = (datetime.utcnow() + timedelta(days=random.randint(1,10))).isoformat() + "Z"
        desc = "Autogenerated task."
        payload = {
            "name": random.choice(taskNames),
            "deadline": deadline,
            "assignedUser": assignedUserID,
            "assignedUserName": assignedUserName,
            "completed": completed,
            "description": desc
        }
        r = requests.post(f"{base}/tasks", headers=headers, json=payload)
        j = r.json()
        if r.status_code >= 400 or not j.get("data"):
            continue
        t = j["data"]
        if assigned and not completed and assignedUserID:
            requests.put(f"{base}/users/{assignedUserID}", headers=headers,
                         json={"pendingTasks":[t["_id"]]}, params={"merge":"true"})

    print(f"{len(userIDs)} users and {taskCount} tasks attempted at {baseurl}:{port}")

if __name__ == "__main__":
    main(sys.argv[1:])
